export const FETCH_USER_MESSAGE_SUCCESS = 'FETCH_USER_MESSAGE_SUCCESS';

export const SET_COLLABORATION = 'SET_COLLABORATION';
export const SET_COLLABORATION_JOINED_PEOPLE = 'SET_COLLABORATION_JOINED_PEOPLE';
