export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS';
export const CHANGE_OFFER_STATUS = 'CHANGE_OFFER_STATUS';
export const COLLABORATION_CREATED_FROM_OFFER = 'COLLABORATION_CREATED_FROM_OFFER';
