export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';
export const REQUEST_SERVICE = 'REQUEST_SERVICE';
export const CLEAR_SERVICE = 'CLEAR_SERVICE';
